### ISSUE TITLE
`TipCategory` enum should include `Performance`

### ISSUE THREAD

**Issue by santisq** [deadlydog/PowerShell.tiPS#25] opened 2023-09-22 21:55 UTC
I think is worth adding this in the `TipCategory` enum, performance is a  important topic in PowerShell in my opinion and there are official articles dedicated to this topic in particular, i.e.: https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations. In addition, often times, PowerShell questions relate to performance issues (from experience by answering questions in SO 😃).

**Comment by santisq** [comment] 2023-09-22 21:57
Proposed change:

```cs
	public enum TipCategory
	{
		Community, // Social events and community resources. e.g. PowerShell Summit, podcasts, etc.
		CoreCmdlet, // Core cmdlet tips. e.g. Get-Process, Get-ChildItem, Get-Content, etc.
		Editor, // Editor tips and extensions. e.g. VSCode, ISE, etc.
		Module, // Modules and module tips. e.g. PSScriptAnalyzer, Pester, etc.
		Syntax, // Syntax tips. e.g. splatting, pipeline, etc.
		Terminal, // Terminal shortcuts and tips. e.g. PSReadLine, Windows Terminal, ConEmu, etc.
		Other, // Tips that don't fit into any of the above categories.
		Performance // Performance related Tips.
	}
```

**Comment by deadlydog** [comment] 2023-09-23 17:22
Great suggestion. My initial concern was that `Performance` might overlap with one of the other categories, and only a single category can be assigned to a tip (by design). The ones it could potentially overlap with are `CoreCmdlet`, `Module`, and `Syntax`. I think though that the overlap should be minimal, and hopefully the intent of the tip should make it obvious which category to choose. e.g. If the tip is showing a syntax change to improve performance, then it is a `Performance` tip.

**Comment by deadlydog** [comment] 2023-09-23 17:41
The new `Performance` category will be available in v0.4.0 of tiPS 🙂 Thanks!

**Closed by deadlydog** 2023-09-23 17:41 UTC

**Comment by santisq** [comment] 2023-09-23 18:50
> My initial concern was that Performance might overlap with one of the other categories...

Would it be that bad if the categories overlapped? It could be a `Flags` enum, then `$tip.Category = [tiPS.TipCategory] - 'Performance, Syntax'` would be possible  😉

**Comment by deadlydog** [comment] 2023-09-23 20:45
I like that suggestion, but want to think on it a bit more. I've moved this flags enum conversation to discussion #28 , so we can discuss it further there.
